/**
 * Mots décoratifs — fond typographique de la séquence anim-can.
 */
export type SequenceWord = {
  text: string
  font: 'changa' | 'unbounded'
  x: number
  y: number
  size: string
  rotate: number
  opacity: number
  weight?: 500 | 700
}

export const SEQUENCE_WORDS_CONFIG = {
  color: '#3D2D75',
  colorAlt: '#5C45A8',
} as const

export const SEQUENCE_WORDS: SequenceWord[] = [
  {
    text: 'Brasserie',
    font: 'changa',
    x: -6,
    y: 4,
    size: 'clamp(4.5rem, 16vw, 11rem)',
    rotate: -8,
    opacity: 0.28,
  },
  {
    text: 'Fraîcheur',
    font: 'unbounded',
    x: 54,
    y: 0,
    size: 'clamp(2.8rem, 9vw, 6.5rem)',
    rotate: 4,
    opacity: 0.22,
    weight: 700,
  },
  {
    text: 'Myrtille',
    font: 'changa',
    x: 34,
    y: 54,
    size: 'clamp(5rem, 18vw, 13rem)',
    rotate: -5,
    opacity: 0.3,
  },
  {
    text: 'Goût',
    font: 'unbounded',
    x: 74,
    y: 34,
    size: 'clamp(3.5rem, 12vw, 8rem)',
    rotate: -14,
    opacity: 0.26,
    weight: 700,
  },
  {
    text: 'Pur',
    font: 'changa',
    x: 4,
    y: 38,
    size: 'clamp(6rem, 22vw, 15rem)',
    rotate: 6,
    opacity: 0.2,
  },
  {
    text: 'Vive',
    font: 'unbounded',
    x: 80,
    y: 68,
    size: 'clamp(2.4rem, 8vw, 5.5rem)',
    rotate: 12,
    opacity: 0.24,
    weight: 500,
  },
  {
    text: 'Zest',
    font: 'changa',
    x: 56,
    y: 76,
    size: 'clamp(4rem, 14vw, 9rem)',
    rotate: -10,
    opacity: 0.22,
  },
  {
    text: 'Nature',
    font: 'unbounded',
    x: -4,
    y: 68,
    size: 'clamp(3rem, 10vw, 7rem)',
    rotate: -6,
    opacity: 0.25,
    weight: 500,
  },
  {
    text: 'Bulles',
    font: 'changa',
    x: 18,
    y: 14,
    size: 'clamp(3.8rem, 13vw, 8.5rem)',
    rotate: 11,
    opacity: 0.23,
  },
  {
    text: 'Artisanal',
    font: 'unbounded',
    x: 8,
    y: 86,
    size: 'clamp(2.2rem, 7vw, 4.8rem)',
    rotate: 3,
    opacity: 0.21,
    weight: 700,
  },
  {
    text: 'Zesté',
    font: 'changa',
    x: 88,
    y: 8,
    size: 'clamp(3.2rem, 11vw, 7.5rem)',
    rotate: -18,
    opacity: 0.26,
  },
  {
    text: 'Savoure',
    font: 'unbounded',
    x: 40,
    y: 24,
    size: 'clamp(2.6rem, 8.5vw, 5.8rem)',
    rotate: 7,
    opacity: 0.2,
    weight: 500,
  },
  {
    text: 'Fruité',
    font: 'unbounded',
    x: 62,
    y: 48,
    size: 'clamp(2.4rem, 7.5vw, 5.2rem)',
    rotate: -9,
    opacity: 0.24,
    weight: 700,
  },
  {
    text: 'Pétillant',
    font: 'changa',
    x: -8,
    y: 48,
    size: 'clamp(3.6rem, 12vw, 8rem)',
    rotate: 5,
    opacity: 0.22,
  },
  {
    text: 'Léger',
    font: 'unbounded',
    x: 28,
    y: 62,
    size: 'clamp(3rem, 10vw, 6.8rem)',
    rotate: -12,
    opacity: 0.27,
    weight: 500,
  },
  {
    text: 'Soleil',
    font: 'changa',
    x: 68,
    y: 18,
    size: 'clamp(4.2rem, 14vw, 9.5rem)',
    rotate: 14,
    opacity: 0.25,
  },
  {
    text: 'Douceur',
    font: 'unbounded',
    x: 46,
    y: 82,
    size: 'clamp(2.5rem, 8vw, 5.5rem)',
    rotate: -4,
    opacity: 0.23,
    weight: 500,
  },
  {
    text: 'Éclat',
    font: 'changa',
    x: 92,
    y: 52,
    size: 'clamp(3.4rem, 11vw, 7.8rem)',
    rotate: 16,
    opacity: 0.21,
  },
  {
    text: 'Corsé',
    font: 'unbounded',
    x: 2,
    y: 22,
    size: 'clamp(2.8rem, 9vw, 6.2rem)',
    rotate: -11,
    opacity: 0.26,
    weight: 700,
  },
  {
    text: 'Vif',
    font: 'changa',
    x: 50,
    y: 38,
    size: 'clamp(5.5rem, 19vw, 12rem)',
    rotate: 3,
    opacity: 0.18,
  },
  {
    text: 'Rafraîchis',
    font: 'unbounded',
    x: 14,
    y: 52,
    size: 'clamp(2rem, 6.5vw, 4.5rem)',
    rotate: 8,
    opacity: 0.22,
    weight: 500,
  },
  {
    text: 'Canette',
    font: 'changa',
    x: 72,
    y: 88,
    size: 'clamp(3.8rem, 13vw, 8.8rem)',
    rotate: -7,
    opacity: 0.28,
  },
  {
    text: 'Plaisir',
    font: 'unbounded',
    x: 36,
    y: 8,
    size: 'clamp(2.6rem, 8vw, 5.8rem)',
    rotate: -15,
    opacity: 0.24,
    weight: 700,
  },
  {
    text: 'Sucré',
    font: 'changa',
    x: 82,
    y: 28,
    size: 'clamp(4.8rem, 16vw, 10.5rem)',
    rotate: 9,
    opacity: 0.2,
  },
]
